### ISSUE TITLE
RCS620S/test.py の import文 のところが間違っている気がする件

### ISSUE THREAD

**Issue by refiute** [ray45422/ekeymgr#1]
``` python
import rc620
```

https://github.com/ray45422/ekeymgr/blob/master/RCS620S/test.py#L3

が

``` python
from rcs620s import Rc620
```

じゃないと動かない気がするんだけど，これって動いてますか？

**Comment by ray45422** [comment]
ありがとうございます。
コミット前にファイル名を修正したのが原因ですね。
諸々修正しておきます。

**Comment by refiute** [comment]
:+1: 

https://github.com/ray45422/ekeymgr/blob/master/RCS620S/test.py#L7

``` python
import rcs620s
r = rcs620s.Rc620(s)
```

のほうが正しかったのか

ファイル名変えるか，コード変更するかはお任せします．

**Comment by ray45422** [comment]
https://github.com/ray45422/ekeymgr/pull/2
直しました
